#!/bin/sh
if [ -z "$1" ]; then
  echo "create_empty_keystore <path_to_keystore>"
  exit 1
fi
 
keytool -genkey -alias foo -keystore $1 -storepass $2 -keypass $2
keytool -delete -alias foo -keystore $1 -storepass $2
